apiVersion: 1

datasources:
  - name: InfluxDB
    uid: influxdb
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: home
      defaultBucket: twc_dashboard
      tlsSkipVerify: true
    secureJsonData:
      token: $INFLUXDB_TOKEN
    isDefault: true
    editable: true
